### ISSUE TITLE
Error installing on Mac with zsh - command not found: lc

### ISSUE THREAD

**Issue by santicros** [matthewp/liblucy#18]
I'm really interested in trying Lucy! Thanks for your work.

## Problem

I tried to do what the install page says on my terminal https://lucylang.org/install/:
``` sh
curl -sSf https://lucylang.org/install.sh | bash
``` 
It went ok! 

Then did
```
lc --help
```
But I get 
```
zsh: command not found: lc
```

Checked my .zshrc config and it automatically added a
```
export PATH="/Users/santicros/.lucy/bin:$PATH"
```

## Solution

I found that removing the final $PATH made it work, so:
```
export PATH="/Users/santicros/.lucy/bin"
```
:D

**Comment by matthewp** [comment]
Did you open a new shell before trying `lc`? The existing shell won't have the directory sourced.

**Comment by santicros** [comment]
Oh I didn't!!! 
I'll undo the change and try it again in a new shell and let you know! Thanks! 😊

**Comment by santicros** [comment]
It worked!! Thanks 👌🏻
Maybe this tip could be added to the Install page :)

**Comment by matthewp** [comment]
It is, but maybe it should be highlighted more so people don't miss it

**Comment by santicros** [comment]
Ohh true, it is! Sorry then haha, but yes maybe could be highlighted more! 😊
