### ISSUE TITLE
Use createMachine insted of Machine

### ISSUE THREAD

**Issue by santicros** [matthewp/liblucy#19]
I think it would be better to use XState's createMachine as it's the recommended syntax and will be the only option on XState v5 :)

**Comment by matthewp** [comment]
Thanks! Is that the only difference?

**Comment by santicros** [comment]
The only small difference is with the Typescript's `TSchema` generic as commented here by Andarist and  David:
https://github.com/davidkpiano/xstate/discussions/1891

So it doesn't change anything else and it's the recommended way now 😁
