### ISSUE TITLE
Add node/browser lib for Lucy

### ISSUE THREAD

**Issue by mattpocock** [matthewp/liblucy#39]
```
import { parseToJson } from '@lucylang/node';

const machine = parseToJson(
`
// Lucy file in here
`
)
```

Many use-cases for this - JS runtime, browser-based tooling, all sorts of cool stuff.

**Comment by matthewp** [comment]
Is this the same thing as #16 ?

**Comment by mattpocock** [comment]
@matthewp Yes! I guess it is the same discussion, just different API. I'll close this and replicate my comment.
